// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Data;

namespace WebApplication4.Migrations
{
    [DbContext(typeof(TutorialContext))]
    [Migration("20181210224552_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("WebApplication4.Models.Movies", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Director");

                    b.HasKey("Title");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WebApplication4.Models.MoviesList", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Movies");

                    b.HasKey("UserID");

                    b.ToTable("MoviesList");
                });

            modelBuilder.Entity("WebApplication4.Models.User", b =>
                {
                    b.Property<string>("user")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fKeyID");

                    b.Property<string>("password");

                    b.HasKey("user");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
